export interface CurrencyOption {
  currencyIcon: string;
  currency: string;
  value: string;
  country_code: string;
}

export const CurrencyOptions: CurrencyOption[] = [
  {
    currencyIcon: "",
    currency: "UAE Dirham (AED)",
    value: "AED",
    country_code: "د.إ1",
  },
  {
    currencyIcon: "",
    currency: "Afghanistan Afghani (AFN)",
    value: "AFN",
    country_code: "؋1",
  },
  {
    currencyIcon: "",
    currency: "Albania Lek (ALL)",
    value: "ALL",
    country_code: "L1",
  },
  {
    currencyIcon: "",
    currency: "Armenia Dram (AMD)",
    value: "AMD",
    country_code: "֏1",
  },
  {
    currencyIcon: "",
    currency: "Netherlands Antillean Guilder (ANG)",
    value: "ANG",
    country_code: "ƒ1",
  },
  {
    currencyIcon: "",
    currency: "Angola Kwanza (AOA)",
    value: "AOA",
    country_code: "Kz1",
  },
  {
    currencyIcon: "",
    currency: "Argentina Peso (ARS)",
    value: "ARS",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Australia Dollar (AUD)",
    value: "AUD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Aruba Florin (AWG)",
    value: "AWG",
    country_code: "ƒ1",
  },
  {
    currencyIcon: "",
    currency: "Azerbaijan Manat (AZN)",
    value: "AZN",
    country_code: "₼1",
  },
  {
    currencyIcon: "",
    currency: "Bosnia and Herzegovina Convertible Marka (BAM)",
    value: "BAM",
    country_code: "KM1",
  },
  {
    currencyIcon: "",
    currency: "Barbados Dollar (BBD)",
    value: "BBD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Bangladesh Taka (BDT)",
    value: "BDT",
    country_code: "৳1",
  },
  {
    currencyIcon: "",
    currency: "Bulgaria Lev (BGN)",
    value: "BGN",
    country_code: "лв1",
  },
  {
    currencyIcon: "",
    currency: "Bahrain Dinar (BHD)",
    value: "BHD",
    country_code: ".د.ب1",
  },
  {
    currencyIcon: "",
    currency: "Burundi Franc (BIF)",
    value: "BIF",
    country_code: "FBu1",
  },
  {
    currencyIcon: "",
    currency: "Bermuda Dollar (BMD)",
    value: "BMD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Brunei Dollar (BND)",
    value: "BND",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Bolivia Boliviano (BOB)",
    value: "BOB",
    country_code: "Bs1",
  },
  {
    currencyIcon: "",
    currency: "Brazil Real (BRL)",
    value: "BRL",
    country_code: "R$1",
  },
  {
    currencyIcon: "",
    currency: "Bahamas Dollar (BSD)",
    value: "BSD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Bhutan Ngultrum (BTN)",
    value: "BTN",
    country_code: "Nu.1",
  },
  {
    currencyIcon: "",
    currency: "Botswana Pula (BWP)",
    value: "BWP",
    country_code: "P1",
  },
  {
    currencyIcon: "",
    currency: "Belarus Ruble (BYN)",
    value: "BYN",
    country_code: "Br1",
  },
  {
    currencyIcon: "",
    currency: "Belize Dollar (BZD)",
    value: "BZD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Canada Dollar (CAD)",
    value: "CAD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Congo Franc (CDF)",
    value: "CDF",
    country_code: "FC1",
  },
  {
    currencyIcon: "",
    currency: "Switzerland Franc (CHF)",
    value: "CHF",
    country_code: "CHF1",
  },
  {
    currencyIcon: "",
    currency: "Chile Peso (CLP)",
    value: "CLP",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "China Yuan (CNY)",
    value: "CNY",
    country_code: "¥1",
  },
  {
    currencyIcon: "",
    currency: "Colombia Peso (COP)",
    value: "COP",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Costa Rica Colon (CRC)",
    value: "CRC",
    country_code: "₡1",
  },
  {
    currencyIcon: "",
    currency: "Cuba Peso (CUP)",
    value: "CUP",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Cape Verde Escudo (CVE)",
    value: "CVE",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Czech Republic Koruna (CZK)",
    value: "CZK",
    country_code: "Kč1",
  },
  {
    currencyIcon: "",
    currency: "Djibouti Franc (DJF)",
    value: "DJF",
    country_code: "Fdj1",
  },
  {
    currencyIcon: "",
    currency: "Denmark Krone (DKK)",
    value: "DKK",
    country_code: "kr1",
  },
  {
    currencyIcon: "",
    currency: "Dominican Republic Peso (DOP)",
    value: "DOP",
    country_code: "RD$1",
  },
  {
    currencyIcon: "",
    currency: "Algeria Dinar (DZD)",
    value: "DZD",
    country_code: "دج1",
  },
  {
    currencyIcon: "",
    currency: "Egypt Pound (EGP)",
    value: "EGP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Eritrea Nakfa (ERN)",
    value: "ERN",
    country_code: "Nfk1",
  },
  {
    currencyIcon: "",
    currency: "Ethiopia Birr (ETB)",
    value: "ETB",
    country_code: "Br1",
  },
  {
    currencyIcon: "",
    currency: "Euro (EUR)",
    value: "EUR",
    country_code: "€1",
  },
  {
    currencyIcon: "",
    currency: "Fiji Dollar (FJD)",
    value: "FJD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Falkland Islands Pound (FKP)",
    value: "FKP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Faroe Islands Króna (FOK)",
    value: "FOK",
    country_code: "kr1",
  },
  {
    currencyIcon: "",
    currency: "British Pounds (GBP)",
    value: "GBP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Georgia Lari (GEL)",
    value: "GEL",
    country_code: "₾1",
  },
  {
    currencyIcon: "",
    currency: "Guernsey Pound (GGP)",
    value: "GGP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Ghana Cedi (GHS)",
    value: "GHS",
    country_code: "₵1",
  },
  {
    currencyIcon: "",
    currency: "Gibraltar Pound (GIP)",
    value: "GIP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Gambia Dalasi (GMD)",
    value: "GMD",
    country_code: "D1",
  },
  {
    currencyIcon: "",
    currency: "Guinea Franc (GNF)",
    value: "GNF",
    country_code: "FG1",
  },
  {
    currencyIcon: "",
    currency: "Guatemala Quetzal (GTQ)",
    value: "GTQ",
    country_code: "Q1",
  },
  {
    currencyIcon: "",
    currency: "Guyana Dollar (GYD)",
    value: "GYD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Hong Kong Dollar (HKD)",
    value: "HKD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Honduras Lempira (HNL)",
    value: "HNL",
    country_code: "L1",
  },
  {
    currencyIcon: "",
    currency: "Croatia Kuna (HRK)",
    value: "HRK",
    country_code: "kn1",
  },
  {
    currencyIcon: "",
    currency: "Haiti Gourde (HTG)",
    value: "HTG",
    country_code: "G1",
  },
  {
    currencyIcon: "",
    currency: "Hungary Forint (HUF)",
    value: "HUF",
    country_code: "Ft1",
  },
  {
    currencyIcon: "",
    currency: "Indonesia Rupiah (IDR)",
    value: "IDR",
    country_code: "Rp1",
  },
  {
    currencyIcon: "",
    currency: "Israel Shekel (ILS)",
    value: "ILS",
    country_code: "₪1",
  },
  {
    currencyIcon: "",
    currency: "Isle of Man Pound (IMP)",
    value: "IMP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Indian Rupee (INR)",
    value: "INR",
    country_code: "₹1",
  },
  {
    currencyIcon: "",
    currency: "Iraq Dinar (IQD)",
    value: "IQD",
    country_code: "ع.د1",
  },
  {
    currencyIcon: "",
    currency: "Iran Rial (IRR)",
    value: "IRR",
    country_code: "﷼1",
  },
  {
    currencyIcon: "",
    currency: "Iceland Krona (ISK)",
    value: "ISK",
    country_code: "kr1",
  },
  {
    currencyIcon: "",
    currency: "Jersey Pound (JEP)",
    value: "JEP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Jamaica Dollar (JMD)",
    value: "JMD",
    country_code: "J$1",
  },
  {
    currencyIcon: "",
    currency: "Jordan Dinar (JOD)",
    value: "JOD",
    country_code: "د.ا1",
  },
  {
    currencyIcon: "",
    currency: "Japan Yen (JPY)",
    value: "JPY",
    country_code: "¥1",
  },
  {
    currencyIcon: "",
    currency: "Kenya Shilling (KES)",
    value: "KES",
    country_code: "KSh1",
  },
  {
    currencyIcon: "",
    currency: "Kyrgyzstan Som (KGS)",
    value: "KGS",
    country_code: "лв1",
  },
  {
    currencyIcon: "",
    currency: "Cambodia Riel (KHR)",
    value: "KHR",
    country_code: "៛1",
  },
  {
    currencyIcon: "",
    currency: "Kiribati Dollar (KID)",
    value: "KID",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Comorian Franc (KMF)",
    value: "KMF",
    country_code: "CF1",
  },
  {
    currencyIcon: "",
    currency: "South Korea Won (KRW)",
    value: "KRW",
    country_code: "₩1",
  },
  {
    currencyIcon: "",
    currency: "Kuwait Dinar (KWD)",
    value: "KWD",
    country_code: "د.ك1",
  },
  {
    currencyIcon: "",
    currency: "Cayman Islands Dollar (KYD)",
    value: "KYD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Kazakhstan Tenge (KZT)",
    value: "KZT",
    country_code: "₸1",
  },
  {
    currencyIcon: "",
    currency: "Laos Kip (LAK)",
    value: "LAK",
    country_code: "₭1",
  },
  {
    currencyIcon: "",
    currency: "Lebanon Pound (LBP)",
    value: "LBP",
    country_code: "ل.ل1",
  },
  {
    currencyIcon: "",
    currency: "Sri Lanka Rupee (LKR)",
    value: "LKR",
    country_code: "Rs1",
  },
  {
    currencyIcon: "",
    currency: "Liberia Dollar (LRD)",
    value: "LRD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Lesotho Loti (LSL)",
    value: "LSL",
    country_code: "L1",
  },
  {
    currencyIcon: "",
    currency: "Libya Dinar (LYD)",
    value: "LYD",
    country_code: "ل.د1",
  },
  {
    currencyIcon: "",
    currency: "Morocco Dirham (MAD)",
    value: "MAD",
    country_code: "د.م.1",
  },
  {
    currencyIcon: "",
    currency: "Moldova Leu (MDL)",
    value: "MDL",
    country_code: "L1",
  },
  {
    currencyIcon: "",
    currency: "Madagascar Ariary (MGA)",
    value: "MGA",
    country_code: "Ar1",
  },
  {
    currencyIcon: "",
    currency: "Macedonia Denar (MKD)",
    value: "MKD",
    country_code: "ден1",
  },
  {
    currencyIcon: "",
    currency: "Myanmar Kyat (MMK)",
    value: "MMK",
    country_code: "K1",
  },
  {
    currencyIcon: "",
    currency: "Mongolia Tugrik (MNT)",
    value: "MNT",
    country_code: "₮1",
  },
  {
    currencyIcon: "",
    currency: "Macau Pataca (MOP)",
    value: "MOP",
    country_code: "P1",
  },
  {
    currencyIcon: "",
    currency: "Mauritania Ouguiya (MRU)",
    value: "MRU",
    country_code: "UM1",
  },
  {
    currencyIcon: "",
    currency: "Mauritius Rupee (MUR)",
    value: "MUR",
    country_code: "₨1",
  },
  {
    currencyIcon: "",
    currency: "Maldives Rufiyaa (MVR)",
    value: "MVR",
    country_code: "ރ1",
  },
  {
    currencyIcon: "",
    currency: "Malawi Kwacha (MWK)",
    value: "MWK",
    country_code: "MK1",
  },
  {
    currencyIcon: "",
    currency: "Mexico Peso (MXN)",
    value: "MXN",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Malaysia Ringgit (MYR)",
    value: "MYR",
    country_code: "RM1",
  },
  {
    currencyIcon: "",
    currency: "Mozambique Metical (MZN)",
    value: "MZN",
    country_code: "MT1",
  },
  {
    currencyIcon: "",
    currency: "Namibia Dollar (NAD)",
    value: "NAD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Nigeria Naira (NGN)",
    value: "NGN",
    country_code: "₦1",
  },
  {
    currencyIcon: "",
    currency: "Nicaragua Cordoba (NIO)",
    value: "NIO",
    country_code: "C$1",
  },
  {
    currencyIcon: "",
    currency: "Norway Krone (NOK)",
    value: "NOK",
    country_code: "kr1",
  },
  {
    currencyIcon: "",
    currency: "Nepal Rupee (NPR)",
    value: "NPR",
    country_code: "₨1",
  },
  {
    currencyIcon: "",
    currency: "New Zealand Dollar (NZD)",
    value: "NZD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Oman Rial (OMR)",
    value: "OMR",
    country_code: "﷼1",
  },
  {
    currencyIcon: "",
    currency: "Panama Balboa (PAB)",
    value: "PAB",
    country_code: "B/.1",
  },
  {
    currencyIcon: "",
    currency: "Peru Sol (PEN)",
    value: "PEN",
    country_code: "S/.1",
  },
  {
    currencyIcon: "",
    currency: "Papua New Guinea Kina (PGK)",
    value: "PGK",
    country_code: "K1",
  },
  {
    currencyIcon: "",
    currency: "Philippines Peso (PHP)",
    value: "PHP",
    country_code: "₱1",
  },
  {
    currencyIcon: "",
    currency: "Pakistan Rupee (PKR)",
    value: "PKR",
    country_code: "₨1",
  },
  {
    currencyIcon: "",
    currency: "Poland Zloty (PLN)",
    value: "PLN",
    country_code: "zł1",
  },
  {
    currencyIcon: "",
    currency: "Paraguay Guarani (PYG)",
    value: "PYG",
    country_code: "₲1",
  },
  {
    currencyIcon: "",
    currency: "Qatar Riyal (QAR)",
    value: "QAR",
    country_code: "ر.ق1",
  },
  {
    currencyIcon: "",
    currency: "Romania Leu (RON)",
    value: "RON",
    country_code: "lei1",
  },
  {
    currencyIcon: "",
    currency: "Serbia Dinar (RSD)",
    value: "RSD",
    country_code: "дин.1",
  },
  {
    currencyIcon: "",
    currency: "Russia Ruble (RUB)",
    value: "RUB",
    country_code: "₽1",
  },
  {
    currencyIcon: "",
    currency: "Rwanda Franc (RWF)",
    value: "RWF",
    country_code: "RF1",
  },
  {
    currencyIcon: "",
    currency: "Saudi Arabia Riyal (SAR)",
    value: "SAR",
    country_code: "﷼1",
  },
  {
    currencyIcon: "",
    currency: "Solomon Islands Dollar (SBD)",
    value: "SBD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Seychelles Rupee (SCR)",
    value: "SCR",
    country_code: "₨1",
  },
  {
    currencyIcon: "",
    currency: "Sudan Pound (SDG)",
    value: "SDG",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Sweden Krona (SEK)",
    value: "SEK",
    country_code: "kr1",
  },
  {
    currencyIcon: "",
    currency: "Singapore Dollar (SGD)",
    value: "SGD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Saint Helena Pound (SHP)",
    value: "SHP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Sierra Leone Leone (SLL)",
    value: "SLL",
    country_code: "Le1",
  },
  {
    currencyIcon: "",
    currency: "Somalia Shilling (SOS)",
    value: "SOS",
    country_code: "S1",
  },
  {
    currencyIcon: "",
    currency: "Suriname Dollar (SRD)",
    value: "SRD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "South Sudan Pound (SSP)",
    value: "SSP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "São Tomé and Príncipe Dobra (STN)",
    value: "STN",
    country_code: "Db1",
  },
  {
    currencyIcon: "",
    currency: "Syria Pound (SYP)",
    value: "SYP",
    country_code: "£1",
  },
  {
    currencyIcon: "",
    currency: "Eswatini Lilangeni (SZL)",
    value: "SZL",
    country_code: "E1",
  },
  {
    currencyIcon: "",
    currency: "Thailand Baht (THB)",
    value: "THB",
    country_code: "฿1",
  },
  {
    currencyIcon: "",
    currency: "Tajikistan Somoni (TJS)",
    value: "TJS",
    country_code: "ЅМ1",
  },
  {
    currencyIcon: "",
    currency: "Turkmenistan Manat (TMT)",
    value: "TMT",
    country_code: "m1",
  },
  {
    currencyIcon: "",
    currency: "Tunisia Dinar (TND)",
    value: "TND",
    country_code: "د.ت1",
  },
  {
    currencyIcon: "",
    currency: "Tonga Paʻanga (TOP)",
    value: "TOP",
    country_code: "T$1",
  },
  {
    currencyIcon: "",
    currency: "Turkey Lira (TRY)",
    value: "TRY",
    country_code: "₺1",
  },
  {
    currencyIcon: "",
    currency: "Trinidad and Tobago Dollar (TTD)",
    value: "TTD",
    country_code: "TT$1",
  },
  {
    currencyIcon: "",
    currency: "Tuvalu Dollar (TVD)",
    value: "TVD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Taiwan Dollar (TWD)",
    value: "TWD",
    country_code: "NT$1",
  },
  {
    currencyIcon: "",
    currency: "Tanzania Shilling (TZS)",
    value: "TZS",
    country_code: "TSh1",
  },
  {
    currencyIcon: "",
    currency: "Ukraine Hryvnia (UAH)",
    value: "UAH",
    country_code: "₴1",
  },
  {
    currencyIcon: "",
    currency: "Uganda Shilling (UGX)",
    value: "UGX",
    country_code: "USh1",
  },
  {
    currencyIcon: "",
    currency: "US Dollar (USD)",
    value: "USD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "Uruguay Peso (UYU)",
    value: "UYU",
    country_code: "$U1",
  },
  {
    currencyIcon: "",
    currency: "Uzbekistan Som (UZS)",
    value: "UZS",
    country_code: "soʻm1",
  },
  {
    currencyIcon: "",
    currency: "Venezuela Bolívar (VES)",
    value: "VES",
    country_code: "Bs.S1",
  },
  {
    currencyIcon: "",
    currency: "Vietnam Dong (VND)",
    value: "VND",
    country_code: "₫1",
  },
  {
    currencyIcon: "",
    currency: "Vanuatu Vatu (VUV)",
    value: "VUV",
    country_code: "VT1",
  },
  {
    currencyIcon: "",
    currency: "Samoa Tala (WST)",
    value: "WST",
    country_code: "WS$1",
  },
  {
    currencyIcon: "",
    currency: "Central African CFA Franc (XAF)",
    value: "XAF",
    country_code: "FCFA1",
  },
  {
    currencyIcon: "",
    currency: "East Caribbean Dollar (XCD)",
    value: "XCD",
    country_code: "$1",
  },
  {
    currencyIcon: "",
    currency: "West African CFA Franc (XOF)",
    value: "XOF",
    country_code: "CFA1",
  },
  {
    currencyIcon: "",
    currency: "CFP Franc (XPF)",
    value: "XPF",
    country_code: "₣1",
  },
  {
    currencyIcon: "",
    currency: "Yemen Rial (YER)",
    value: "YER",
    country_code: "﷼1",
  },
  {
    currencyIcon: "",
    currency: "South Africa Rand (ZAR)",
    value: "ZAR",
    country_code: "R1",
  },
  {
    currencyIcon: "",
    currency: "Zambia Kwacha (ZMW)",
    value: "ZMW",
    country_code: "ZK1",
  },
  {
    currencyIcon: "",
    currency: "Zimbabwe Dollar (ZWL)",
    value: "ZWL",
    country_code: "$1",
  },
];
