import type { Metadata } from "next";
import { Metropolis } from "@/helpers/fonts";
// import ProgressBar from "@/components/progress-bar/progress-bar.component";
import "./globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Monieplug",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Metropolis.variable}>
        <div>
          <div>
            {children}
            {/* <ProgressBar /> */}
          </div>
        </div>
      </body>
    </html>
  );
}
